-- Crear base de datos Pokédex
CREATE DATABASE IF NOT EXISTS pokedex CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pokedex;

-- Tabla de tipos de Pokémon
CREATE TABLE tipos (
                       id INT AUTO_INCREMENT PRIMARY KEY,
                       nombre VARCHAR(50) NOT NULL UNIQUE,
                       imagen_ruta_tipo VARCHAR(255)
);

-- Tabla principal de Pokémon
CREATE TABLE pokemon (
                         id INT AUTO_INCREMENT PRIMARY KEY,
                         numero_identificador INT NOT NULL UNIQUE,
                         nombre VARCHAR(100) NOT NULL,
                         tipo_id INT NOT NULL,
                         descripcion TEXT,
                         imagen_ruta VARCHAR(255),
                         FOREIGN KEY (tipo_id) REFERENCES tipos(id)
);

INSERT INTO tipos (id, nombre, imagen_ruta_tipo) VALUES
                                                     (1, 'Normal', 'public/img/tipos/normal.png'),
                                                     (2, 'Fuego', 'public/img/tipos/fuego.png'),
                                                     (3, 'Agua', 'public/img/tipos/agua.png'),
                                                     (4, 'Eléctrico', 'public/img/tipos/electrico.png'),
                                                     (5, 'Planta', 'public/img/tipos/planta.png'),
                                                     (6, 'Hielo', 'public/img/tipos/hielo.png'),
                                                     (7, 'Lucha', 'public/img/tipos/lucha.png'),
                                                     (8, 'Veneno', 'public/img/tipos/veneno.png'),
                                                     (9, 'Tierra', 'public/img/tipos/tierra.png'),
                                                     (10, 'Volador', 'public/img/tipos/volador.png'),
                                                     (11, 'Psíquico', 'public/img/tipos/psiquico.png'),
                                                     (12, 'Bicho', 'public/img/tipos/bicho.png'),
                                                     (13, 'Roca', 'public/img/tipos/roca.png'),
                                                     (14, 'Fantasma', 'public/img/tipos/fantasma.png'),
                                                     (15, 'Dragón', 'public/img/tipos/dragon.png'),
                                                     (18, 'Hada', 'public/img/tipos/hada.png');



-- Insertar los 151 primeros Pokémon
INSERT INTO pokemon (numero_identificador, nombre, tipo_id, descripcion, imagen_ruta) VALUES
                                                                                          (1, 'Bulbasaur', 5, 'Un Pokémon cuadrúpedo de color verde con manchas más oscuras. Tiene un bulbo en el lomo que crece con la edad.', 'public/img/1.png'),
                                                                                          (2, 'Ivysaur', 5, 'Cuando el bulbo de su lomo se hincha, desprende un aroma dulce y emite más energía.', 'public/img/2.png'),
                                                                                          (3, 'Venusaur', 5, 'Su planta desprende un aroma dulce que intensifica las emociones de otros Pokémon.', 'public/img/3.png'),
                                                                                          (4, 'Charmander', 2, 'La llama de su cola indica sus emociones. Arde con más fuerza cuando está emocionado.', 'public/img/4.png'),
                                                                                          (5, 'Charmeleon', 2, 'Cuando agita su ardiente cola, eleva gradualmente la temperatura a su alrededor.', 'public/img/5.png'),
                                                                                          (6, 'Charizard', 2, 'Escupe fuego que es tan caliente que puede derretir cualquier cosa.', 'public/img/6.png'),
                                                                                          (7, 'Squirtle', 3, 'Su caparazón se endurece tras el nacimiento. Se vuelve más resistente y adquiere un color más intenso.', 'public/img/7.png'),
                                                                                          (8, 'Wartortle', 3, 'Se considera un símbolo de longevidad. Los ejemplares más longevos tienen musgo sobre el caparazón.', 'public/img/8.png'),
                                                                                          (9, 'Blastoise', 3, 'Los chorros de agua de su caparazón pueden agujerear el acero grueso.', 'public/img/9.png'),
                                                                                          (10, 'Caterpie', 12, 'Para protegerse, desprende un hedor horrible por las antenas de su cabeza.', 'public/img/10.png'),
                                                                                          (11, 'Metapod', 12, 'Su cuerpo se endurece para proteger su interior blando. Permanece inmóvil para evolucionar.', 'public/img/11.png'),
                                                                                          (12, 'Butterfree', 12, 'Adora el néctar de las flores. Puede localizar incluso las menores cantidades de polen.', 'public/img/12.png'),
                                                                                          (13, 'Weedle', 12, 'Come hojas vorazmente. Su aguijón venenoso en la cabeza es muy peligroso.', 'public/img/13.png'),
                                                                                          (14, 'Kakuna', 12, 'Casi incapaz de moverse, endurece su caparazón para protegerse de los depredadores.', 'public/img/14.png'),
                                                                                          (15, 'Beedrill', 12, 'Vuela a gran velocidad y ataca con los aguijones venenosos de sus brazos.', 'public/img/15.png'),
                                                                                          (16, 'Pidgey', 10, 'Muy dócil. Si es atacado, levanta arena con las alas para protegerse.', 'public/img/16.png'),
                                                                                          (17, 'Pidgeotto', 10, 'Tiene una vista muy aguda. Es capaz de divisar un Magikarp que nade en un río desde el aire.', 'public/img/17.png'),
                                                                                          (18, 'Pidgeot', 10, 'Cuando caza, vuela muy cerca del agua y atrapa a sus distraídas presas.', 'public/img/18.png'),
                                                                                          (19, 'Rattata', 1, 'Vive en cualquier lugar. Es muy resistente y se reproduce rápidamente.', 'public/img/19.png'),
                                                                                          (20, 'Raticate', 1, 'Lima sus colmillos royendo objetos duros. Usa sus colmillos para atacar.', 'public/img/20.png'),
                                                                                          (21, 'Spearow', 10, 'Come bichos en zonas de hierba alta. Debe batir mucho las alas para mantenerse en el aire.', 'public/img/21.png'),
                                                                                          (22, 'Fearow', 10, 'Con sus enormes y magníficas alas, puede seguir volando sin tener que aterrizar para descansar.', 'public/img/22.png'),
                                                                                          (23, 'Ekans', 8, 'Se mueve en silencio y sin hacer ruido. Come huevos de Pidgey y Spearow.', 'public/img/23.png'),
                                                                                          (24, 'Arbok', 8, 'Para intimidar al enemigo, hincha el pecho y emite sonidos escalofriantes.', 'public/img/24.png'),
                                                                                          (25, 'Pikachu', 4, 'Cuando varios de estos Pokémon se juntan, su electricidad puede causar tormentas.', 'public/img/25.png'),
                                                                                          (26, 'Raichu', 4, 'Su cola hace las veces de toma de tierra para protegerse de su propia descarga.', 'public/img/26.png'),
                                                                                          (27, 'Sandshrew', 9, 'Vive en zonas áridas y desérticas. Se protege del calor enterrándose en la arena.', 'public/img/27.png'),
                                                                                          (28, 'Sandslash', 9, 'Se enrolla como una pelota para atacar. También sirve para protegerse de sus enemigos.', 'public/img/28.png'),
                                                                                          (29, 'Nidoran♀', 8, 'Aunque pequeño, su cuerno venenoso es muy peligroso. Tiene un oído más fino que el macho.', 'public/img/29.png'),
                                                                                          (30, 'Nidorina', 8, 'Cuando está con sus amigas se vuelve menos combativo. Emite ultrasonidos para alertar a otros.', 'public/img/30.png'),
                                                                                          (31, 'Nidoqueen', 9, 'El cuerpo de este Pokémon está recubierto de escamas duras como el acero.', 'public/img/31.png'),
                                                                                          (32, 'Nidoran♂', 8, 'Sus músculos desarrollados le dan fuerza para lanzar puñetazos que pueden pulverizar cualquier cosa.', 'public/img/32.png'),
                                                                                          (33, 'Nidorino', 8, 'Clava su cuerno venenoso con fuerza en el enemigo. Sus cuernos se endurecen al crecer.', 'public/img/33.png'),
                                                                                          (34, 'Nidoking', 9, 'Es reconocido por su piel dura como una roca y su largo cuerno, con el cual puede quebrar hasta diamantes.', 'public/img/34.png'),
                                                                                          (35, 'Clefairy', 18, 'Su aspecto mágico atrae a muchos. Es muy raro verlo, por lo que se cree que trae felicidad.', 'public/img/35.png'),
                                                                                          (36, 'Clefable', 18, 'Camina con sigilo para no ser visto. Se dice que su oído es tan fino que puede oír una aguja caer.', 'public/img/36.png'),
                                                                                          (37, 'Vulpix', 2, 'Al nacer solo tiene una cola, pero a medida que crece, esta se va dividiendo desde la punta.', 'public/img/37.png'),
                                                                                          (38, 'Ninetales', 2, 'Muy vengativo. Dicen que puede mantener rencor durante 1000 años, así que hay que tener cuidado.', 'public/img/38.png'),
                                                                                          (39, 'Jigglypuff', 18, 'Cuando sus enormes ojos se llenan de lágrimas, todos los que los ven sienten ganas de consolarlo.', 'public/img/39.png'),
                                                                                          (40, 'Wigglytuff', 18, 'Su piel es tan suave que si dos de ellos se acurrucan juntos, no querrán separarse nunca.', 'public/img/40.png'),
                                                                                          (41, 'Zubat', 10, 'Permanece quieto en lugares oscuros durante el día. No tiene ojos, así que usa ultrasonidos.', 'public/img/41.png'),
                                                                                          (42, 'Golbat', 10, 'Adora la sangre fresca. Se dice que en las noches oscuras aparece para chupar sangre.', 'public/img/42.png'),
                                                                                          (43, 'Oddish', 5, 'Durante el día permanece plantado. Por la noche, planta semillas y hace crecer plantas.', 'public/img/43.png'),
                                                                                          (44, 'Gloom', 5, 'El fluido que gotea de su boca no es baba, sino néctar dulce con un aroma horrible.', 'public/img/44.png'),
                                                                                          (45, 'Vileplume', 5, 'Tiene los pétalos más grandes del mundo. Los agita para esparcir polen tóxico.', 'public/img/45.png'),
                                                                                          (46, 'Paras', 12, 'Lleva dos setas parásitas llamadas tochukaso a cuestas, que crecen con él.', 'public/img/46.png'),
                                                                                          (47, 'Parasect', 12, 'Las setas en su espalda controlan cada movimiento de este Pokémon.', 'public/img/47.png'),
                                                                                          (48, 'Venonat', 12, 'Vive a la sombra de árboles altos donde come bichos. Atrae a las presas con sus ojos.', 'public/img/48.png'),
                                                                                          (49, 'Venomoth', 12, 'Esparce escamas de colores cuando bate las alas. Estas escamas son venenosas.', 'public/img/49.png'),
                                                                                          (50, 'Diglett', 9, 'Vive un metro por debajo del suelo. Se alimenta de raíces de árboles.', 'public/img/50.png'),
                                                                                          (51, 'Dugtrio', 9, 'Un trío de Diglett. Puede cavar hasta 60 km de profundidad bajo tierra.', 'public/img/51.png'),
                                                                                          (52, 'Meowth', 1, 'Adora los objetos redondos. Deambula por las calles en busca de monedas perdidas.', 'public/img/52.png'),
                                                                                          (53, 'Persian', 1, 'Aunque es de constitución esbelta, puede caminar tan silenciosamente que no se le oye.', 'public/img/53.png'),
                                                                                          (54, 'Psyduck', 3, 'Mientras medita, ejerce poderes psíquicos de los que no era consciente.', 'public/img/54.png'),
                                                                                          (55, 'Golduck', 3, 'A menudo se le confunde con el monstruo del lago Ness cuando nada por los lagos.', 'public/img/55.png'),
                                                                                          (56, 'Mankey', 7, 'Vive en las copas de los árboles en grandes grupos. Es muy fácil que se enfade.', 'public/img/56.png'),
                                                                                          (57, 'Primeape', 7, 'Siempre está furioso y persigue a su objetivo hasta atraparlo. No puede distinguir amigo de enemigo.', 'public/img/57.png'),
                                                                                          (58, 'Growlithe', 2, 'Tiene un sentido del olfato excelente. Es capaz de identificar las emociones de otros seres.', 'public/img/58.png'),
                                                                                          (59, 'Arcanine', 2, 'Este Pokémon es admirado por su belleza. Corre ágilmente como si tuviera alas.', 'public/img/59.png'),
                                                                                          (60, 'Poliwag', 3, 'Su piel es tan fina que se pueden ver sus órganos internos en espiral.', 'public/img/60.png'),
                                                                                          (61, 'Poliwhirl', 3, 'Capaz de vivir dentro o fuera del agua. Fuera del agua, suda para mantener su cuerpo pegajoso.', 'public/img/61.png'),
                                                                                          (62, 'Poliwrath', 3, 'Un hábil nadador tanto en océanos como en lagos. Su poderoso físico nunca se cansa.', 'public/img/62.png'),
                                                                                          (63, 'Abra', 11, 'Usa poderes extrasensoriales para detectar el peligro y teletransportarse a un lugar seguro.', 'public/img/63.png'),
                                                                                          (64, 'Kadabra', 11, 'Emite ondas alfa especiales de su cuerpo que inducen dolores de cabeza solo por estar cerca.', 'public/img/64.png'),
                                                                                          (65, 'Alakazam', 11, 'Su cerebro nunca deja de crecer, por lo que su cabeza se vuelve demasiado pesada para su cuello.', 'public/img/65.png'),
                                                                                          (66, 'Machop', 7, 'Adora hacer ejercicio. Aunque ejercite su cuerpo todo el día, nunca se cansa.', 'public/img/66.png'),
                                                                                          (67, 'Machoke', 7, 'Su formidable cuerpo nunca se cansa. Ayuda a la gente con trabajos pesados.', 'public/img/67.png'),
                                                                                          (68, 'Machamp', 7, 'Usando sus cuatro brazos, puede dar una serie de 1000 puñetazos en 2 segundos.', 'public/img/68.png'),
                                                                                          (69, 'Bellsprout', 5, 'Un Pokémon carnívoro que se traga cualquier cosa que se mueva. Su boca puede abrirse para cualquier tamaño.', 'public/img/69.png'),
                                                                                          (70, 'Weepinbell', 5, 'Escupe un fluido ácido que disuelve cualquier cosa. También puede lanzar hojas afiladas.', 'public/img/70.png'),
                                                                                          (71, 'Victreebel', 5, 'Se dice que vive en enormes colonias en lo profundo de las selvas, aunque nadie ha regresado.', 'public/img/71.png'),
                                                                                          (72, 'Tentacool', 3, 'Deriva en mares poco profundos. Los pescadores a veces pescan este Pokémon por error.', 'public/img/72.png'),
                                                                                          (73, 'Tentacruel', 3, 'Los tentáculos se contraen y lanzan ácido sobre su presa. Puede atrapar hasta 80 presas a la vez.', 'public/img/73.png'),
                                                                                          (74, 'Geodude', 9, 'Vive en montañas. Su cuerpo rocoso es muy duro y resistente a ataques.', 'public/img/74.png'),
                                                                                          (75, 'Graveler', 9, 'Puede rodar por colinas empinadas para moverse rápidamente y escapar de enemigos.', 'public/img/75.png'),
                                                                                          (76, 'Golem', 9, 'Su cuerpo es extremadamente duro. Un ataque con fuerza media no puede moverlo ni un centímetro.', 'public/img/76.png'),
                                                                                          (77, 'Ponyta', 2, 'Sus crines y cola arden con fuego cuando corre rápido. Puede superar los 150 km/h.', 'public/img/77.png'),
                                                                                          (78, 'Rapidash', 2, 'Corre a una velocidad increíble. Sus llamas aumentan cuando se enfada o se emociona.', 'public/img/78.png'),
                                                                                          (79, 'Slowpoke', 3, 'Se mueve muy lentamente y su cerebro es lento. A veces se olvida de lo que estaba haciendo.', 'public/img/79.png'),
                                                                                          (80, 'Slowbro', 3, 'Una Shellder se ha adherido a su cola. Aunque Slowbro no lo note, ha adquirido más poder.', 'public/img/80.png'),
                                                                                          (81, 'Magnemite', 4, 'Usa su campo magnético para flotar y moverse. Atrae objetos metálicos a su alrededor.', 'public/img/81.png'),
                                                                                          (82, 'Magneton', 4, 'Tres Magnemite unidos. Sus campos magnéticos pueden interferir con la electricidad cercana.', 'public/img/82.png'),
                                                                                          (83, 'Farfetch’d', 10, 'Siempre lleva un tallo de planta. Se dice que quien se lo quite recibirá mala suerte.', 'public/img/83.png'),
                                                                                          (84, 'Doduo', 10, 'Tiene dos cabezas y corre muy rápido. Si una cabeza está distraída, la otra sigue corriendo.', 'public/img/84.png'),
                                                                                          (85, 'Dodrio', 10, 'Tres cabezas con personalidades distintas. Coordinan sus movimientos para cazar juntos.', 'public/img/85.png'),
                                                                                          (86, 'Seel', 3, 'Vive en zonas heladas. Su grueso pelaje lo mantiene caliente incluso en aguas frías.', 'public/img/86.png'),
                                                                                          (87, 'Dewgong', 3, 'Nadador ágil. Su cuerpo hidrodinámico le permite moverse por el agua con gran velocidad.', 'public/img/87.png'),
                                                                                          (88, 'Grimer', 8, 'Se forma en zonas contaminadas. Su cuerpo está compuesto por residuos tóxicos.', 'public/img/88.png'),
                                                                                          (89, 'Muk', 8, 'Su cuerpo es tan pegajoso que atrapa todo lo que toca, incluyendo Pokémon pequeños.', 'public/img/89.png'),
                                                                                          (90, 'Shellder', 3, 'Vive dentro de su concha dura. Puede cerrar su concha instantáneamente para protegerse.', 'public/img/90.png'),
                                                                                          (91, 'Cloyster', 3, 'Su concha es extremadamente dura. Puede disparar púas de hielo como defensa.', 'public/img/91.png'),
                                                                                          (92, 'Gastly', 11, 'Su cuerpo es gaseoso. Puede atravesar paredes y desaparecer a voluntad.', 'public/img/92.png'),
                                                                                          (93, 'Haunter', 11, 'Su presencia provoca escalofríos. Puede levitar y atacar sin ser visto.', 'public/img/93.png'),
                                                                                          (94, 'Gengar', 11, 'Se esconde en sombras. Tiene la capacidad de absorber la energía vital de otros.', 'public/img/94.png'),
                                                                                          (95, 'Onix', 9, 'Su cuerpo de roca está compuesto por enormes segmentos. Puede excavar túneles rápidamente.', 'public/img/95.png'),
                                                                                          (96, 'Drowzee', 11, 'Hace que las personas y Pokémon pierdan energía con su mirada hipnótica.', 'public/img/96.png'),
                                                                                          (97, 'Hypno', 11, 'Se dice que arrastra a las personas a un sueño profundo y luego se alimenta de su energía.', 'public/img/97.png'),
                                                                                          (98, 'Krabby', 9, 'Sus pinzas son muy fuertes. Defiende su territorio y lucha por alimento.', 'public/img/98.png'),
                                                                                          (99, 'Kingler', 9, 'Una pinza más grande que la otra. La usa para luchar y para comunicarse.', 'public/img/99.png'),
                                                                                          (100, 'Voltorb', 4, 'Se confunde fácilmente con una Pokéball. Puede explotar si se altera.', 'public/img/100.png'),
                                                                                          (101, 'Electrode', 4, 'Cuando se enfada, puede generar una explosión que arrasa con todo a su alrededor.', 'public/img/101.png'),
                                                                                          (102, 'Exeggcute', 5, 'Un conjunto de semillas que piensa como un grupo. Puede comunicarse telepáticamente.', 'public/img/102.png'),
                                                                                          (103, 'Exeggutor', 5, 'Sus cabezas están conectadas. Cada una tiene su propia mente, aunque se muevan juntas.', 'public/img/103.png'),
                                                                                          (104, 'Cubone', 1, 'Siempre lleva el cráneo de su madre fallecida. Llora por la pérdida.', 'public/img/104.png'),
                                                                                          (105, 'Marowak', 1, 'Defiende su territorio con su hueso. Es fuerte y resistente.', 'public/img/105.png'),
                                                                                          (106, 'Hitmonlee', 7, 'Su pierna puede estirarse de forma increíble. Su patada es extremadamente poderosa.', 'public/img/106.png'),
                                                                                          (107, 'Hitmonchan', 7, 'Especialista en golpes de boxeo. Puede lanzar una serie de puñetazos a gran velocidad.', 'public/img/107.png'),
                                                                                          (108, 'Lickitung', 11, 'Su lengua es muy larga y pegajosa. Usa la lengua para capturar presas.', 'public/img/108.png'),
                                                                                          (109, 'Koffing', 8, 'Emite gases tóxicos continuamente. Su gas puede ser mortal si se concentra.', 'public/img/109.png'),
                                                                                          (110, 'Weezing', 8, 'Sigue liberando gases venenosos. Puede crear una nube tóxica que cubre varias cuadras.', 'public/img/110.png'),
                                                                                          (111, 'Rhyhorn', 9, 'Corre a gran velocidad por terrenos difíciles. Su cuerpo es muy duro.', 'public/img/111.png'),
                                                                                          (112, 'Rhydon', 9, 'Su cuerno puede perforar cualquier roca. Es muy territorial.', 'public/img/112.png'),
                                                                                          (113, 'Chansey', 18, 'Muy amigable. Cuida a otros Pokémon enfermos y les da huevos nutritivos.', 'public/img/113.png'),
                                                                                          (114, 'Tangela', 5, 'Su cuerpo está cubierto por enredaderas. Es muy difícil ver su forma real.', 'public/img/114.png'),
                                                                                          (115, 'Kangaskhan', 1, 'Protege ferozmente a su cría. Puede pelear contra enemigos muy grandes.', 'public/img/115.png'),
                                                                                          (116, 'Horsea', 3, 'Usa chorros de agua para atacar y defenderse. Nada con rapidez.', 'public/img/116.png'),
                                                                                          (117, 'Seadra', 3, 'Vive en aguas profundas. Ataca con chorros de agua muy potentes.', 'public/img/117.png'),
                                                                                          (118, 'Goldeen', 3, 'Sus movimientos en el agua son elegantes. Puede saltar fuera del agua con gran altura.', 'public/img/118.png'),
                                                                                          (119, 'Seaking', 3, 'Lanza ataques con sus cuernos. Nada con gran velocidad en ríos y lagos.', 'public/img/119.png'),
                                                                                          (120, 'Staryu', 3, 'Su núcleo brilla intensamente. Vive en el fondo del mar.', 'public/img/120.png'),
                                                                                          (121, 'Starmie', 3, 'Su núcleo central gira rápidamente. Puede emitir ondas de energía.', 'public/img/121.png'),
                                                                                          (122, 'Mr. Mime', 11, 'Crea barreras invisibles con gestos de sus manos. Muy hábil en imitar movimientos.', 'public/img/122.png'),
                                                                                          (123, 'Scyther', 12, 'Extremadamente rápido. Sus brazos cortan todo lo que tocan.', 'public/img/123.png'),
                                                                                          (124, 'Jynx', 11, 'Puede hipnotizar enemigos con su baile y su canto.', 'public/img/124.png'),
                                                                                          (125, 'Electabuzz', 4, 'Genera electricidad en su cuerpo. Puede lanzarla en ataques precisos.', 'public/img/125.png'),
                                                                                          (126, 'Magmar', 2, 'Su cuerpo emite calor intenso. Puede derretir rocas con su fuego.', 'public/img/126.png'),
                                                                                          (127, 'Pinsir', 12, 'Usa sus poderosas pinzas para capturar y aplastar a sus enemigos.', 'public/img/127.png'),
                                                                                          (128, 'Tauros', 1, 'Muy agresivo. Ataca con embestidas poderosas cuando se enfada.', 'public/img/128.png'),
                                                                                          (129, 'Magikarp', 3, 'Muy débil, pero si sobrevive mucho tiempo, puede evolucionar.', 'public/img/129.png'),
                                                                                          (130, 'Gyarados', 3, 'Extremadamente feroz y destructivo. Puede generar tormentas masivas.', 'public/img/130.png'),
                                                                                          (131, 'Lapras', 3, 'Usado como transporte acuático. Muy inteligente y gentil.', 'public/img/131.png'),
                                                                                          (132, 'Ditto', 11, 'Puede transformarse en cualquier Pokémon que vea.', 'public/img/132.png'),
                                                                                          (133, 'Eevee', 1, 'Puede evolucionar en muchas formas distintas según las condiciones.', 'public/img/133.png'),
                                                                                          (134, 'Vaporeon', 3, 'Puede fusionarse con agua. Sus ataques de agua son muy poderosos.', 'public/img/134.png'),
                                                                                          (135, 'Jolteon', 4, 'Su cuerpo está cargado de electricidad. Puede moverse extremadamente rápido.', 'public/img/135.png'),
                                                                                          (136, 'Flareon', 2, 'Su fuego interior puede elevar la temperatura de su cuerpo a niveles extremos.', 'public/img/136.png'),
                                                                                          (137, 'Porygon', 11, 'Un Pokémon virtual. Puede entrar en sistemas informáticos.', 'public/img/137.png'),
                                                                                          (138, 'Omanyte', 12, 'Un fósil reanimado. Sus tentáculos le ayudan a moverse.', 'public/img/138.png'),
                                                                                          (139, 'Omastar', 12, 'Pokémon fósil. Sus tentáculos son extremadamente fuertes y ágiles.', 'public/img/139.png'),
                                                                                          (140, 'Kabuto', 12, 'Otro Pokémon fósil. Su caparazón lo protege de los depredadores.', 'public/img/140.png'),
                                                                                          (141, 'Kabutops', 12, 'Sus afiladas garras cortan con facilidad. Vive en zonas acuáticas poco profundas.', 'public/img/141.png'),
                                                                                          (142, 'Aerodactyl', 9, 'Un fósil volador. Muy rápido y feroz.', 'public/img/142.png'),
                                                                                          (143, 'Snorlax', 1, 'Duerme la mayor parte del día. Su tamaño le permite resistir ataques.', 'public/img/143.png'),
                                                                                          (144, 'Articuno', 3, 'Un ave legendaria de hielo. Puede crear tormentas de nieve.', 'public/img/144.png'),
                                                                                          (145, 'Zapdos', 4, 'Un ave legendaria de electricidad. Puede generar relámpagos enormes.', 'public/img/145.png'),
                                                                                          (146, 'Moltres', 2, 'Un ave legendaria de fuego. Su aparición anuncia incendios forestales.', 'public/img/146.png'),
                                                                                          (147, 'Dratini', 3, 'Muy raro. Crece lentamente y se vuelve más fuerte con los años.', 'public/img/147.png'),
                                                                                          (148, 'Dragonair', 3, 'Su cuerpo es muy largo y elegante. Puede controlar el clima con su energía.', 'public/img/148.png'),
                                                                                          (149, 'Dragonite', 3, 'Fuerte y veloz. Puede volar grandes distancias y generar huracanes.', 'public/img/149.png'),
                                                                                          (150, 'Mewtwo', 11, 'Creado por ingeniería genética. Su poder psíquico es extraordinario.', 'public/img/150.png'),
                                                                                          (151, 'Mew', 11, 'Pokémon legendario. Se dice que contiene el ADN de todos los Pokémon.', 'public/img/151.png');

